version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.0'
    steps:
      - checkout
      - run: git clone git@github.com:MementoMoriSchoolProject/Project_Se_Node_Server.git ~/backend
      - node/with-cache:
          steps:
            - run: cd ~/backend
            - run: cd ~/backend && pwd && echo "installing backend" && npm install
      - run:
          command: cd ~/backend && npm run dev
          background: true
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8000/graphql
            :
      - run: cd ~/project
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run graphql:download
      - run: npm run graphql:generate
      - run: npm run build