version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.0'
    steps:
      - checkout
      - run: git clone git@github.com:MementoMoriSchoolProject/Project_Se_Node_Server.git ~/backend
      - node/with-cache:
          steps:
            - run: cd ~/backend/Project_Se_Node_Server
            - run: npm install
      - run: npm run dev
      - run: cd ~
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run graphql:download
      - run: npm run graphql:generate
      - run: npm run build