version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '12.0'
    steps:
      # does some git magic
      - checkout
      # clone the backend into a special backend folder
      - run: git clone git@github.com:MementoMoriSchoolProject/Project_Se_Node_Server.git ~/backend
      - node/with-cache:
          steps:
            # npm install on the backend
            # this command finds the branch the frontend is on,
            # and attempts to switch to that same branch name on the backend,
            # so that it can compare the frontend changes to the API changes
            # that belong with it
            - run:
                name: "npm install backend"
                command: |
                  CIRCLE_PR_BRANCH=$(git rev-parse --abbrev-ref HEAD)
                  export CIRCLE_PR_BRANCH
                  if [ "$CIRCLE_PR_BRANC" = "master" ]
                  then
                    CIRCLE_PR_BRANCH=development
                    export CIRCLE_PR_BRANCH
                  fi
                  cd ~/backend
                  git pull
                  (git checkout $CIRCLE_PR_BRANCH || git checkout development)
                  npm install
      # run the backend in the background
      - run:
          command: cd ~/backend && npm run dev
          background: true
      # wait till the backend is up by continously checking if we can connect or not
      - run:
          shell: /bin/sh
          command: |
            wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8000/graphql
            :
      - node/with-cache:
          steps:
            # npm install on the frontend
            - run: npm install
      # download graphql definition from the backend
      - run: npm run graphql:download
      # generate graphql types from the definition
      - run: npm run graphql:generate
      # build the frontend
      - run: npm run build
